language: node_js

node_js: 10

branches:
  except:
  - /^published\/.*$/

script: |
  ./build.sh

before_deploy: |
  export TRAVIS_TAG="published/$(jq -j '.version' < ./src/package.json)"

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh
    on:
      branch: release
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    skip_cleanup: true
    name: "Alan Interface Consumer v${TRAVIS_TAG}"
    on:
      branch: release
